### ISSUE TITLE
Invalid API key - t in empty fields

### ISSUE THREAD

**Issue by HHMediaDesign** [yikesinc/yikes-inc-easy-mailchimp-extender#180]
I am getting this error (below) and the front end of the website says this even though I have selected the only available list on my MailChimp Account: The list doesn't exist! Make sure you have imported the list on the 'Manage List Forms' page.

Another strange thing is that there is default text in all of the "empty" fields - just showing a single lower case 't'.

Hack? Can you help?
sunnysidemall.ca

Thanks,
Hillary

Fatal error: Uncaught exception 'Mailchimp_Invalid_ApiKey' with message 'Invalid MailChimp API Key: t' in /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php:346 Stack trace: #0 /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php(325): wpyksMCAPI->castError(Array) #1 /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(663): wpyksMCAPI->call('lists/list', Array) #2 /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/class.yksemeBase.php(613): yksemeBase->getListsData() #3 /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/pages/lists.php(2084): yksemeBase->getLists() #4 /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/p in /nfs/c08/h03/mnt/117246/domains/sunnysidemall.ca/html/wp-content/plugins/yikes-inc-easy-mailchimp-extender/classes/MCAPI_2.0.class.verify_false.php on line 346

**Comment by EvanHerman** [comment]
Hi

"Mailchimp_Invalid_ApiKey' with message 'Invalid MailChimp API Key: t' " states that you have entered "t" into the API key field. 

You shouldn't be seeing the error message and input fields. You can try toggling ssl verify peer to true on the debug page. 

It appears you've entered an invalid API key into the field thus why none of the fields are displaying properly. 


Thanks,
Evan
